import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import articles from "../data.json";

export default function Home({ articles }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>FOMO</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3>Interesting Articles</h3>
        <div style={{ marginBottom: "40px" }}>
          Recent reads by{" "}
          <a href="https://twitter.com/skorytnicki" target="_blank" rel="noopener noreferrer">
            Szymon Korytnicki
          </a>
        </div>
        {articles.map((article) => {
          return (
            <article
              key={article.id}
              style={{
                padding: "20px",
                margin: "10px",
                maxWidth: "600px",
                width: "100%",
                border: "1px solid #ccc",
                position: "relative",
              }}
            >
              <Rating rating={article.rating} />
              <header>
                <small>
                  <a href={`/articles/${article.id}`}>
                    <Time timestamp={article.timestamp} />
                  </a>
                </small>
                <h2>
                  <a
                    style={{ display: "block", textOverflow: "ellipsis", maxWidth: "500px", overflow: "hidden" }}
                    href={article.title}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    {/* TODO use different tag*/}
                    {article.title}
                  </a>{" "}
                </h2>
              </header>
              <div>{article.content}</div>
              <TagsList tags={article.tags} />
              <Button
                onClick={() => {
                  // TODO use website
                  navigator.clipboard.writeText(`https://fomo-bmdr.vercel.app/articles/${article.id}`);
                }}
              >
                Copy URL
              </Button>
            </article>
          );
        })}
      </main>

      <footer className={styles.footer}>
        <div>
          <a href="https://twitter.com/skorytnicki" target="_blank" rel="noopener noreferrer">
            FOMO by @skorytnicki
          </a>
        </div>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  return {
    props: {
      articles,
    },
  };
}

function Time({ timestamp }) {
  const [state, setState] = useState(false);
  const router = useRouter();
  useEffect(() => {
    if (router.isReady) {
      setState(true);
    }
  }, [router.isReady]);

  if (!state) {
    return <span>&nbsp;</span>;
  }
  return <time dateTime={new Date(timestamp * 1000).toISOString()}>{new Date(timestamp * 1000).toLocaleString()}</time>;
}

function Button({ children, onClick }) {
  return (
    <button
      style={{
        padding: "10px",
        borderRadius: "5px",
        border: "1px solid #ccc",
        background: "#fff",
        cursor: "pointer",
      }}
      onClick={onClick}
    >
      {children}
    </button>
  );
}

function TagsList({ tags }) {
  return (
    <div style={{ padding: "20px", paddingLeft: "0px" }}>
      {tags.split(" ").map((tag) => {
        return (
          <span
            key={tag}
            style={{
              padding: "5px",
              marginRight: "5px",
              borderRadius: "5px",
              border: "1px solid #ccc",
              fontSize: 0.8 + "em",
            }}
          >
            {tag}
          </span>
        );
      })}
    </div>
  );
}

function Rating({ rating }) {
  return (
    <div
      style={{
        position: "absolute",
        top: "10px",
        right: "10px",
        background: getBackground(rating),
        color: "white",
        fontSize: "1.5rem",
        padding: "5px",
      }}
    >
      {rating}
    </div>
  );
}

function getBackground(rating) {
  if (rating === "N/A") {
    return "#ccc";
  }
  if (rating < 3) {
    return "red";
  }
  if (rating < 5) {
    return "orange";
  }
  return "green";
}
