import Link from "next/link";
import { getArticle } from "../../../utils/articles";
export const revalidate = 3600; // revalidate the data at most every hour

export const metadata = {
  title: "Article",
  // description: "Generated by Next.js",
};

export default async function Page({ params: { id } }: { params: { id: string } }) {
  const article = await getArticle(id);

  return (
    <div>
      <h2>{article.title}</h2>
      <p>{article.description}</p>
      <Link target="_blank" href={article.link}>
        Visit
      </Link>
    </div>
  );
}
